name: ado-ml-batch-train
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip==19.2.3
  - jupyter==1.0.0
  - nb_conda_kernels==2.2.2
  - papermill==1.2.0
  - pandas==0.23.4
  - scikit-learn==0.21.3
  - lightgbm==2.2.1
  - pip:
      - prompt_toolkit==2.0.9
      - azure-cli==2.0.77
      - azureml-sdk[notebooks,automl]==1.0.85
      - azureml-dataprep>=1.1.35
      - pyarrow>=0.11.0
      - pytest==5.3.4
      - pylint==2.4.4
      - matplotlib
      - git+https://github.com/Microsoft/AI-Utilities.git@version/1.0
